apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hydra-quarkus-4k
  janus-idp.io/tekton: hydra-quarkus-4k
  backstage.io/kubernetes-id: hydra-quarkus-4k
  backstage.io/kubernetes-namespace: rodan-demo 
  app.kubernetes.io/part-of: hydra-quarkus-4k
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
