apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hydra-quarkus-4k
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hydra-quarkus-4k 
  name: hydra-quarkus-4k
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hydra-quarkus-4k 
